name = "MatricesForHomalg"
uuid = "29b9b1b6-efa6-450e-8188-a5a2c25df071"
authors = ["Mohamed Barakat <mohamed.barakat@uni-siegen.de>", "Johanna Knecht <johanna.knecht@student.uni-siegen.de>"]
version = "0.1.3"

[deps]
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"

[compat]
Nemo = "0.48.0, 0.49, 0.50, 0.51"
julia = "1.9, 1.10, 1.11"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
