module MatricesForHomalgSingularExt

using MatricesForHomalg
import Nemo
import Singular

"""
    HomalgRingOfIntegersInSingular()

Return the Singular integer ring ZZ.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> HomalgRingOfIntegersInSingular()
Integer ring
```
"""
MatricesForHomalg.HomalgRingOfIntegersInSingular() = Singular.ZZ

"""
    HomalgFieldOfRationalsInSingular()

Return the Singular rational field QQ.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> HomalgFieldOfRationalsInSingular()
Rational field
```
"""
MatricesForHomalg.HomalgFieldOfRationalsInSingular() = Singular.QQ

"""
    HomalgRingOfIntegersInSingular(n)

Return the Singular residue ring ZZ/nZZ.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> HomalgRingOfIntegersInSingular(3)
Residue ring of integer ring modulo 3
```
"""
MatricesForHomalg.HomalgRingOfIntegersInSingular(n::Int) = Singular.residue_ring(Singular.ZZ, n)[1]

"""
    R[s]

Construct the univariate polynomial ring R[s] over the Singular integers or rationals.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> Singular.ZZ["x"]
Singular polynomial ring (ZZ),(x),(dp(1),C)
```
"""
function Base.getindex(R::Union{Singular.Integers, Singular.Rationals}, s::Union{Char, AbstractString, Symbol})
    return Singular.polynomial_ring(R, [string(s)])[1]
end

"""
    R[s, ss...]

Construct the multivariate polynomial ring R[s, ss...] over the Singular integers or rationals.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> Singular.QQ["x","y"]
Singular polynomial ring (QQ),(x,y),(dp(2),C)
```
"""
function Base.getindex(R::Union{Singular.Integers, Singular.Rationals}, s::Union{Char, AbstractString, Symbol}, ss::Union{Char, AbstractString, Symbol}...)
    return Singular.polynomial_ring(R, [string(s); [string(x) for x in ss]])[1]
end

## assign generating variables
"""
    AssignGeneratingVariables(R::Singular.PolyRing)

Assign the generators of the polynomial ring R as global variables in Main.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, _ = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> AssignGeneratingVariables(R)

julia> x
x

julia> y
y
```
"""
function MatricesForHomalg.AssignGeneratingVariables(R::Singular.PolyRing)
    for (sym, gen) in zip(R.S, Singular.gens(R))
        Core.eval(Main, Expr(:(=), sym, gen))
    end
end

"""
    RingName(Q::Singular.Rationals)

Return the name `"Q"` for the Singular rational field.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> RingName(Singular.QQ)
"Q"
```
"""
function MatricesForHomalg.RingName(Q::Singular.Rationals)
    return "Q"
end

"""
    RingName(Z::Singular.Integers)

Return the name `"Z"` for the Singular integer ring.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> RingName(Singular.ZZ)
"Z"
```
"""
function MatricesForHomalg.RingName(Z::Singular.Integers)
    return "Z"
end

"""
    RingName(R::Singular.PolyRing)

Return a descriptive name string for the polynomial ring R,
including quotient relations when R is a quotient ring.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> RingName(R)
"Q[x,y]"

julia> S = R / [x^2 + y^2 - 1];

julia> RingName(S)
"Q[x,y] / ( x^2 + y^2 - 1 )"
```
"""
function MatricesForHomalg.RingName(R::Singular.PolyRing)
    base = RingName(Singular.base_ring(R))
    vars = join(map(s -> string(s), R.S), ",")
    name = base * "[" * vars * "]"
    if Singular.is_quotient_ring(R)
        I = Singular.quotient_ideal(R)
        rels = join([string(Singular.gens(I)[k]) for k in 1:Singular.ngens(I)], ", ")
        name *= " / ( " * rels * " )"
    end
    return name
end

# Every commutative ring has the invariant basis property
"""
    HasHasInvariantBasisProperty(R::Singular.PolyRing)

Return `true`, since every commutative polynomial ring has the invariant basis property.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, _ = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> HasHasInvariantBasisProperty(R)
true
```
"""
function MatricesForHomalg.HasHasInvariantBasisProperty(::Singular.PolyRing)
    return true
end

"""
    HasInvariantBasisProperty(R::Singular.PolyRing)

Return `true`, since every commutative polynomial ring has the invariant basis property.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, _ = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> HasInvariantBasisProperty(R)
true
```
"""
function MatricesForHomalg.HasInvariantBasisProperty(::Singular.PolyRing)
    return true
end

"""
    R / relations

Construct the quotient ring of R by the ideal generated by `relations`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> R / [x^2 + y^2 - 1]
Singular polynomial quotient ring (QQ),(x,y),(dp(2),C)
```
"""
function Base.:/(R::Singular.PolyRing, relations::Vector)
    I = Singular.Ideal(R, relations...)
    G = Singular.std(I)
    S, indets = Singular.QuotientRing(R, G)
    #for (sym, val) in zip(R.S, indets)
    #    Core.eval(Main, Expr(:(=), sym, val))
    #end
    return S
end

"""
    Indeterminates(R::Singular.PolyRing)

Return the list of generators (indeterminates) of the polynomial ring R.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, _ = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> Indeterminates(R)
spoly{n_Q}[x, y]
```
"""
function MatricesForHomalg.Indeterminates(R::Singular.PolyRing)
    return Singular.gens(R)
end

## Parse a polynomial string into an element of the ring R

function _subst_vars(expr, vars::Dict{Symbol})
    expr isa Symbol && haskey(vars, expr) ? vars[expr] :
    expr isa Expr ? Expr(expr.head, (_subst_vars(a, vars) for a in expr.args)...) :
    expr
end

"""
    (R::Singular.PolyRing)(s::String)

Parse a polynomial expression string `s` into an element of the ring R.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, _ = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> R("x^2 + 2*y")
x^2 + 2*y
```
"""
function (R::Singular.PolyRing)(s::String)
    vars = Dict(sym => g for (sym, g) in zip(R.S, Singular.gens(R)))
    return Core.eval(@__MODULE__, _subst_vars(Meta.parse(s), vars))
end

#function (S::Singular.PolyRing)(f::Singular.spoly)
#    parent(f) == S && return f
#    B = Singular.MPolyBuildCtx(S)
#    for (c, e) in zip(Singular.coefficients(f), Singular.exponent_vectors(f))
#        Singular.push_term!(B, Singular.base_ring(S)(c), e)
#    end
#    return Singular.finish(B)
#end

"""
    HomalgMatrix(entries, r, c, R::Singular.PolyRing)

Construct a Singular matrix of size `r × c` over the polynomial ring R,
with entries given by the (possibly nested) array `entries`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> HomalgMatrix([[x, y], [x^2, y^2]], 2, 2, R)
[x, y
x^2, y^2]
```
"""
function MatricesForHomalg.HomalgMatrix(entries, nr_rows, nr_cols, R::Singular.PolyRing)
    m = Singular.zero_matrix(R, nr_rows, nr_cols)
    flat = vcat(entries...)
    for i in 1:nr_rows, j in 1:nr_cols
        m[i, j] = R(flat[(i - 1) * nr_cols + j])
    end
    return m
end

## HomalgZeroMatrix / HomalgIdentityMatrix for Singular rings

"""
    HomalgZeroMatrix(r, c, R::Singular.PolyRing)

Construct a `(r × c)` zero matrix over the Singular polynomial ring R.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, _ = Singular.polynomial_ring(Singular.QQ, ["x"]);

julia> HomalgZeroMatrix(2, 3, R)
[0, 0, 0
0, 0, 0]
```
"""
function MatricesForHomalg.HomalgZeroMatrix(r, c, R::Singular.PolyRing)
    return Singular.zero_matrix(R, r, c)
end

"""
    HomalgIdentityMatrix(r, R::Singular.PolyRing)

Construct a `(r × r)` identity matrix over the Singular polynomial ring R.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, _ = Singular.polynomial_ring(Singular.QQ, ["x"]);

julia> HomalgIdentityMatrix(2, R)
[1, 0
0, 1]
```
"""
function MatricesForHomalg.HomalgIdentityMatrix(r, R::Singular.PolyRing)
    return Singular.identity_matrix(R, Int(r))
end

## RandomMatrix for Singular rings
"""
    RandomMatrix(r, c, R::Singular.PolyRing)

Construct a random `(r × c)` matrix over the Singular polynomial ring R,
with entries that are random scalar multiples of monomials in the generators of R.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, _ = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> m = RandomMatrix(2, 3, R);

julia> NumberRows(m), NumberColumns(m)
(2, 3)
```
"""
function MatricesForHomalg.RandomMatrix(r, c, R::Singular.PolyRing)
    m = Singular.zero_matrix(R, r, c)
    for i in 1:r, j in 1:c
        m[i, j] = R(rand(-5:5)) * prod([rand([zero(R); one(R); Singular.gens(R)...]) for i in 1:rand([1, 1, 1, 2, 2, 3])])
    end
    return m
end

"""
    -(mat::Singular.smatrix)

Return the negation of the Singular matrix `mat`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2]], 2, 2, R);

julia> -A
[-x, -y
-x^2, -y^2]
```
"""
function Base.:-(mat::Singular.smatrix)
    R = Singular.base_ring(mat)
    result = Singular.zero_matrix(R, Singular.nrows(mat), Singular.ncols(mat))
    for i in 1:Singular.nrows(mat), j in 1:Singular.ncols(mat)
        result[i, j] = -mat[i, j]
    end
    return result
end

## NumberRows / NumberColumns / HomalgRing / TransposedMatrix for smatrix

"""
    NumberRows(mat::Singular.smatrix)

Return the number of rows of the Singular matrix `mat`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2]], 2, 2, R);

julia> NumberRows(A)
2
```
"""
function MatricesForHomalg.NumberRows(mat::Singular.smatrix)
    return Singular.nrows(mat)
end

"""
    NumberColumns(mat::Singular.smatrix)

Return the number of columns of the Singular matrix `mat`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2]], 2, 2, R);

julia> NumberColumns(A)
2
```
"""
function MatricesForHomalg.NumberColumns(mat::Singular.smatrix)
    return Singular.ncols(mat)
end

"""
    HomalgRing(mat::Singular.smatrix)

Return the base ring of the Singular matrix `mat`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2]], 2, 2, R);

julia> HomalgRing(A)
Singular polynomial ring (QQ),(x,y),(dp(2),C)
```
"""
function MatricesForHomalg.HomalgRing(mat::Singular.smatrix)
    return Singular.base_ring(mat)
end

"""
    TransposedMatrix(mat::Singular.smatrix)

Return the transpose of the Singular matrix `mat`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2]], 2, 2, R);

julia> TransposedMatrix(A)
[x, x^2
y, y^2]
```
"""
function MatricesForHomalg.TransposedMatrix(mat::Singular.smatrix)
    return Singular.transpose(mat)
end

## IsZero / IsOne / IsEmptyMatrix / IsSymmetricMatrix for smatrix

"""
    IsZero(mat::Singular.smatrix)

Return `true` if `mat` is a zero matrix, otherwise `false`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, _ = Singular.polynomial_ring(Singular.QQ, ["x"]);

julia> IsZero(HomalgZeroMatrix(2, 3, R))
true
```
"""
function MatricesForHomalg.IsZero(mat::Singular.smatrix)
    return Singular.iszero(mat)
end

"""
    IsOne(mat::Singular.smatrix)

Return `true` if `mat` is an identity matrix, otherwise `false`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, _ = Singular.polynomial_ring(Singular.QQ, ["x"]);

julia> IsOne(HomalgIdentityMatrix(2, R))
true
```
"""
function MatricesForHomalg.IsOne(mat::Singular.smatrix)
    R = Singular.base_ring(mat)
    nr = Singular.nrows(mat)
    nc = Singular.ncols(mat)
    nr == nc || return false
    for i in 1:nr, j in 1:nc
        if i == j
            mat[i, j] == R(1) || return false
        else
            Singular.iszero(mat[i, j]) || return false
        end
    end
    return true
end

"""
    IsEmptyMatrix(mat::Singular.smatrix)

Return `true` if `mat` has zero rows or zero columns, otherwise `false`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, _ = Singular.polynomial_ring(Singular.QQ, ["x"]);

julia> IsEmptyMatrix(HomalgZeroMatrix(0, 3, R))
true
```
"""
function MatricesForHomalg.IsEmptyMatrix(mat::Singular.smatrix)
    return Singular.nrows(mat) == 0 || Singular.ncols(mat) == 0
end

"""
    IsSymmetricMatrix(mat::Singular.smatrix)

Return `true` if `mat` equals its transpose, otherwise `false`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [y, x]], 2, 2, R);

julia> IsSymmetricMatrix(A)
true
```
"""
function MatricesForHomalg.IsSymmetricMatrix(mat::Singular.smatrix)
    nr = Singular.nrows(mat)
    nc = Singular.ncols(mat)
    nr == nc || return false
    for i in 1:nr, j in (i+1):nc
        mat[i, j] == mat[j, i] || return false
    end
    return true
end

## CertainRows / CertainColumns for smatrix

"""
    CertainRows(mat::Singular.smatrix, list)

Return the submatrix of `mat` consisting of the rows specified by `list`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2]], 2, 2, R);

julia> CertainRows(A, [2])
[x^2, y^2]
```
"""
function MatricesForHomalg.CertainRows(mat::Singular.smatrix, list)
    R = Singular.base_ring(mat)
    nc = Singular.ncols(mat)
    nr_new = length(list)
    if nr_new == 0
        return Singular.zero_matrix(R, 0, nc)
    end
    result = Singular.zero_matrix(R, nr_new, nc)
    for (i, row) in enumerate(list)
        for j in 1:nc
            result[i, j] = mat[Int(row), j]
        end
    end
    return result
end

"""
    CertainColumns(mat::Singular.smatrix, list)

Return the submatrix of `mat` consisting of the columns specified by `list`.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2]], 2, 2, R);

julia> CertainColumns(A, [1])
[x
x^2]
```
"""
function MatricesForHomalg.CertainColumns(mat::Singular.smatrix, list)
    R = Singular.base_ring(mat)
    nr = Singular.nrows(mat)
    nc_new = length(list)
    if nc_new == 0
        return Singular.zero_matrix(R, nr, 0)
    end
    result = Singular.zero_matrix(R, nr, nc_new)
    for (j, col) in enumerate(list)
        for i in 1:nr
            result[i, j] = mat[i, Int(col)]
        end
    end
    return result
end

## UnionOfRows / UnionOfColumns for Singular rings

"""
    UnionOfRows(R::Singular.PolyRing, nr_cols, list)

Vertically stack the matrices in `list` into a single matrix with `nr_cols` columns over R.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2]], 2, 2, R);

julia> UnionOfRows(R, 2, [CertainRows(A, [1]), CertainRows(A, [2])])
[x, y
x^2, y^2]
```
"""
function MatricesForHomalg.UnionOfRows(R::Singular.PolyRing, nr_cols, list)
    if length(list) == 0
        return Singular.zero_matrix(R, 0, nr_cols)
    end
    total_rows = sum(Singular.nrows(m) for m in list)
    result = Singular.zero_matrix(R, total_rows, nr_cols)
    row_offset = 0
    for m in list
        nr = Singular.nrows(m)
        for i in 1:nr, j in 1:nr_cols
            result[row_offset + i, j] = m[i, j]
        end
        row_offset += nr
    end
    return result
end

"""
    UnionOfColumns(R::Singular.PolyRing, nr_rows, list)

Horizontally concatenate the matrices in `list` into a single matrix with `nr_rows` rows over R.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2]], 2, 2, R);

julia> UnionOfColumns(R, 2, [CertainColumns(A, [1]), CertainColumns(A, [2])])
[x, y
x^2, y^2]
```
"""
function MatricesForHomalg.UnionOfColumns(R::Singular.PolyRing, nr_rows, list)
    if length(list) == 0
        return Singular.zero_matrix(R, nr_rows, 0)
    end
    total_cols = sum(Singular.ncols(m) for m in list)
    result = Singular.zero_matrix(R, nr_rows, total_cols)
    col_offset = 0
    for m in list
        nc = Singular.ncols(m)
        for i in 1:nr_rows, j in 1:nc
            result[i, col_offset + j] = m[i, j]
        end
        col_offset += nc
    end
    return result
end

## KroneckerMat for smatrix

"""
    KroneckerMat(mat1::Singular.smatrix, mat2::Singular.smatrix)

Return the Kronecker product of `mat1` and `mat2` over a Singular polynomial ring.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> M1 = HomalgMatrix([[x, R(0)], [R(0), y]], 2, 2, R);

julia> M2 = HomalgMatrix([[R(1), R(1)], [R(1), R(1)]], 2, 2, R);

julia> KroneckerMat(M1, M2)
[x, x, 0, 0
x, x, 0, 0
0, 0, y, y
0, 0, y, y]
```
"""
function MatricesForHomalg.KroneckerMat(mat1::Singular.smatrix, mat2::Singular.smatrix)
    R = Singular.base_ring(mat1)
    r1, c1 = Singular.nrows(mat1), Singular.ncols(mat1)
    r2, c2 = Singular.nrows(mat2), Singular.ncols(mat2)
    result = Singular.zero_matrix(R, r1 * r2, c1 * c2)
    for i1 in 1:r1, j1 in 1:c1
        a = mat1[i1, j1]
        for i2 in 1:r2, j2 in 1:c2
            result[(i1 - 1) * r2 + i2, (j1 - 1) * c2 + j2] = a * mat2[i2, j2]
        end
    end
    return result
end

## HomalgDiagonalMatrix for Singular rings

"""
    HomalgDiagonalMatrix(diagonal_entries, R::Singular.PolyRing)

Construct a diagonal matrix over the Singular polynomial ring R with the given diagonal entries.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> HomalgDiagonalMatrix([x, y], R)
[x, 0
0, y]
```
"""
function MatricesForHomalg.HomalgDiagonalMatrix(diagonal_entries, R::Singular.PolyRing)
    n = length(diagonal_entries)
    result = Singular.zero_matrix(R, n, n)
    for i in 1:n
        result[i, i] = R(diagonal_entries[i])
    end
    return result
end

"""
    SyzygiesOfRows(A::Singular.smatrix)

Return a matrix whose rows generate the left kernel of A,
i.e. all rows K satisfying K * A = 0.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2], [x*y, x*y]], 3, 2, R);

julia> S = SyzygiesOfRows(A)
[x + y, -1, -1]

julia> iszero(S * A)
true
```
"""
function MatricesForHomalg.SyzygiesOfRows(A::Singular.smatrix)
    R = Singular.base_ring(A)
    # Columns of transpose(A) are the rows of A.
    # Module from those columns, syz finds relations among them,
    # i.e. vectors (a1,...,am) with a1*row1 + ... + am*rowm = 0.
    M = Singular.Module(Singular.transpose(A))
    S = Singular.syz(M)
    # Matrix(S) has syzygy vectors as columns; transpose to get rows.
    if Singular.iszero(S)
        # syz returns zero module if there are no syzygies, but we want a zero matrix.
        return Singular.zero_matrix(R, 0, Singular.nrows(A))
    else
        return Singular.transpose(Singular.Matrix(S))
    end
end

"""
    SyzygiesOfColumns(A::Singular.smatrix)

Return a matrix whose columns generate the right kernel of A,
i.e. all columns K satisfying A * K = 0.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, x^2, x*y], [y, y^2, x*y]], 2, 3, R);

julia> S = SyzygiesOfColumns(A)
[x + y
-1
-1]

julia> iszero(A * S)
true
```
"""
function MatricesForHomalg.SyzygiesOfColumns(A::Singular.smatrix)
    # Columns of A are generators of a submodule of R^m.
    # syz finds vectors (a1,...,an) with a1*col1 + ... + an*coln = 0,
    # which is exactly A * [a1,...,an]^T = 0.
    M = Singular.Module(A)
    S = Singular.syz(M)
    if Singular.iszero(S)
        # syz returns zero module if there are no syzygies, but we want a zero matrix.
        R = Singular.base_ring(A)
        return Singular.zero_matrix(R, Singular.ncols(A), 0)
    else
        return Singular.Matrix(S)
    end
end

"""
    SyzygiesOfRows(A::Singular.smatrix, N::Singular.smatrix)

Return a matrix K whose rows satisfy K * A ∈ row span of N,
i.e. the relative left kernel of A modulo N.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2]], 2, 2, R);

julia> N = HomalgMatrix([[x, y]], 1, 2, R);

julia> K = SyzygiesOfRows(A, N)
[1, 0]

julia> iszero(DecideZeroRows(K * A, N))
true
```
"""
function MatricesForHomalg.SyzygiesOfRows(A::Singular.smatrix, N::Singular.smatrix)
    At = Singular.transpose(A)
    Nt = Singular.transpose(N)
    St = MatricesForHomalg.SyzygiesOfColumns(At, Nt)
    return Singular.transpose(St)
end

"""
    SyzygiesOfColumns(A::Singular.smatrix, N::Singular.smatrix)

Return a matrix K whose columns satisfy A * K ∈ column span of N,
i.e. the relative right kernel of A modulo N.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, x^2], [y, y^2]], 2, 2, R);

julia> N = HomalgMatrix([[x], [y]], 2, 1, R);

julia> K = SyzygiesOfColumns(A, N)
[1
0]

julia> iszero(DecideZeroColumns(A * K, N))
true
```
"""
function MatricesForHomalg.SyzygiesOfColumns(A::Singular.smatrix, N::Singular.smatrix)
    # modulo(M_A, M_N) computes the kernel of R^n -> M_A / (M_A ∩ M_N),
    # i.e. vectors (a1,...,an) such that a1*col1(A) + ... + an*coln(A) ∈ Im(N).
    M_A = Singular.Module(A)
    M_N = Singular.Module(N)
    S = Singular.modulo(M_A, M_N)
    if Singular.iszero(S)
        R = Singular.base_ring(A)
        return Singular.zero_matrix(R, Singular.ncols(A), 0)
    else
        return Singular.Matrix(S)
    end
end

## BasisOfRows / BasisOfColumns

"""
    BasisOfColumns(A::Singular.smatrix)

Return a matrix whose columns form a Gröbner basis for the column module generated by A.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, x^2, x*y], [y, y^2, x*y]], 2, 3, R);

julia> BasisOfColumns(A)
[x, 0
y, x*y - y^2]
```
"""
function MatricesForHomalg.BasisOfColumns(A::Singular.smatrix)
    M = Singular.Module(A)
    G = Singular.std(M)
    if Singular.iszero(G)
        R = Singular.base_ring(A)
        return Singular.zero_matrix(R, Singular.nrows(A), 0)
    else
        return Singular.Matrix(G)
    end
end

"""
    BasisOfRows(A::Singular.smatrix)

Return a matrix whose rows form a Gröbner basis for the row module generated by A.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2], [x*y, x*y]], 3, 2, R);

julia> BasisOfRows(A)
[x, y
0, x*y - y^2]
```
"""
function MatricesForHomalg.BasisOfRows(A::Singular.smatrix)
    return Singular.transpose(MatricesForHomalg.BasisOfColumns(Singular.transpose(A)))
end

## DecideZeroRows / DecideZeroColumns

"""
    DecideZeroColumns(B::Singular.smatrix, A::Singular.smatrix)

Reduce each column of B modulo the column module of A.
Returns a matrix whose columns are the normal forms of the columns of B with respect to the column Gröbner basis of A.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> B = HomalgMatrix([[x^2], [y^2]], 2, 1, R);

julia> N = HomalgMatrix([[x], [y]], 2, 1, R);

julia> DecideZeroColumns(B, N)
[0
-x*y + y^2]
```
"""
function MatricesForHomalg.DecideZeroColumns(B::Singular.smatrix, A::Singular.smatrix)
    M_A = Singular.Module(A)
    G = Singular.std(M_A)
    M_B = Singular.Module(B)
    R = Singular.reduce(M_B, G)
    return Singular.Matrix(R)
end

"""
    DecideZeroRows(B::Singular.smatrix, A::Singular.smatrix)

Reduce each row of B modulo the row module of A.
Returns a matrix whose rows are the normal forms of the rows of B with respect to the row Gröbner basis of A.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> B = HomalgMatrix([[x^2, y^2]], 1, 2, R);

julia> N = HomalgMatrix([[x, y]], 1, 2, R);

julia> DecideZeroRows(B, N)
[0, -x*y + y^2]
```
"""
function MatricesForHomalg.DecideZeroRows(B::Singular.smatrix, A::Singular.smatrix)
    return Singular.transpose(MatricesForHomalg.DecideZeroColumns(Singular.transpose(B), Singular.transpose(A)))
end

## LeftDivide / RightDivide (two-argument: solve AX = B)

"""
    SafeLeftDivide(A::Singular.smatrix, B::Singular.smatrix)

Solve the linear system A * X = B over a Singular polynomial ring and return X.
Throws an error if no solution exists.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, R(0)], [R(0), y]], 2, 2, R);

julia> B = HomalgMatrix([[x^2, R(0)], [R(0), y^2]], 2, 2, R);

julia> SafeLeftDivide(A, B)
[x, 0
0, y]
```
"""
function MatricesForHomalg.SafeLeftDivide(A::Singular.smatrix, B::Singular.smatrix)
    M_A = Singular.Module(A)
    M_B = Singular.Module(B)
    T, rest = Singular.lift(M_A, M_B)
    if !Singular.iszero(rest)
        error("Unable to solve linear system")
    end
    return Singular.Matrix(T)
end

"""
    LeftDivide(A::Singular.smatrix, B::Singular.smatrix)

Solve the linear system A * X = B over a Singular polynomial ring and return X,
or return `"fail"` if no solution exists.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, R(0)], [R(0), y]], 2, 2, R);

julia> B = HomalgMatrix([[x^2, R(0)], [R(0), y^2]], 2, 2, R);

julia> LeftDivide(A, B)
[x, 0
0, y]

julia> LeftDivide(HomalgMatrix([[x, x]], 1, 2, R), HomalgMatrix([[R(1)]], 1, 1, R))
"fail"
```
"""
function MatricesForHomalg.LeftDivide(A::Singular.smatrix, B::Singular.smatrix)
    try
        return MatricesForHomalg.SafeLeftDivide(A, B)
    catch
        return "fail"
    end
end

"""
    SafeRightDivide(B::Singular.smatrix, A::Singular.smatrix)

Solve the linear system X * A = B over a Singular polynomial ring and return X.
Throws an error if no solution exists.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, R(0)], [R(0), y]], 2, 2, R);

julia> B = HomalgMatrix([[x^2, R(0)], [R(0), y^2]], 2, 2, R);

julia> SafeRightDivide(B, A)
[x, 0
0, y]
```
"""
function MatricesForHomalg.SafeRightDivide(B::Singular.smatrix, A::Singular.smatrix)
    return Singular.transpose(MatricesForHomalg.SafeLeftDivide(Singular.transpose(A), Singular.transpose(B)))
end

"""
    RightDivide(B::Singular.smatrix, A::Singular.smatrix)

Solve the linear system X * A = B over a Singular polynomial ring and return X,
or return `"fail"` if no solution exists.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, R(0)], [R(0), y]], 2, 2, R);

julia> B = HomalgMatrix([[x^2, R(0)], [R(0), y^2]], 2, 2, R);

julia> RightDivide(B, A)
[x, 0
0, y]

julia> RightDivide(HomalgMatrix([[R(1)]], 1, 1, R), HomalgMatrix([[x], [x]], 2, 1, R))
"fail"
```
"""
function MatricesForHomalg.RightDivide(B::Singular.smatrix, A::Singular.smatrix)
    try
        return MatricesForHomalg.SafeRightDivide(B, A)
    catch
        return "fail"
    end
end

## LeftDivide / RightDivide (three-argument: solve AX + LY = B)

"""
    SafeLeftDivide(A::Singular.smatrix, B::Singular.smatrix, L::Singular.smatrix)

Find X such that B - A * X is in the column span of L,
i.e. solve A * X + L * Y = B for X. Throws an error if no such X exists.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, R(0)], [R(0), y]], 2, 2, R);

julia> L = HomalgZeroMatrix(2, 0, R);

julia> B = HomalgMatrix([[x^2, R(0)], [R(0), y^2]], 2, 2, R);

julia> SafeLeftDivide(A, B, L)
[x, 0
0, y]
```
"""
function MatricesForHomalg.SafeLeftDivide(A::Singular.smatrix, B::Singular.smatrix, L::Singular.smatrix)
    R = Singular.base_ring(A)
    nr_rows = Singular.nrows(A)
    nr_cols_a = Singular.ncols(A)
    nr_cols_l = Singular.ncols(L)
    # Combine columns of A and L into one matrix
    AL = Singular.zero_matrix(R, nr_rows, nr_cols_a + nr_cols_l)
    for i in 1:nr_rows, j in 1:nr_cols_a
        AL[i, j] = A[i, j]
    end
    for i in 1:nr_rows, j in 1:nr_cols_l
        AL[i, nr_cols_a + j] = L[i, j]
    end
    M_AL = Singular.Module(AL)
    M_B = Singular.Module(B)
    T, rest = Singular.lift(M_AL, M_B)
    if !Singular.iszero(rest)
        error("Unable to solve linear system")
    end
    T_mat = Singular.Matrix(T)
    # Extract the first nr_cols_a rows (corresponding to A)
    result = Singular.zero_matrix(R, nr_cols_a, Singular.ncols(T_mat))
    for i in 1:nr_cols_a, j in 1:Singular.ncols(T_mat)
        result[i, j] = T_mat[i, j]
    end
    return result
end

"""
    LeftDivide(A::Singular.smatrix, B::Singular.smatrix, L::Singular.smatrix)

Find X such that B - A * X is in the column span of L,
or return `"fail"` if no such X exists.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, R(0)], [R(0), y]], 2, 2, R);

julia> L = HomalgZeroMatrix(2, 0, R);

julia> B = HomalgMatrix([[x^2, R(0)], [R(0), y^2]], 2, 2, R);

julia> LeftDivide(A, B, L)
[x, 0
0, y]
```
"""
function MatricesForHomalg.LeftDivide(A::Singular.smatrix, B::Singular.smatrix, L::Singular.smatrix)
    try
        return MatricesForHomalg.SafeLeftDivide(A, B, L)
    catch
        return "fail"
    end
end

"""
    SafeRightDivide(B::Singular.smatrix, A::Singular.smatrix, L::Singular.smatrix)

Find X such that B - X * A is in the row span of L,
i.e. solve X * A + Y * L = B for X. Throws an error if no such X exists.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, R(0)], [R(0), y]], 2, 2, R);

julia> L = HomalgMatrix([[R(1), R(0)], [R(0), R(1)]], 2, 2, R);

julia> B = HomalgMatrix([[x^2, R(0)], [R(0), y^2]], 2, 2, R);

julia> SafeRightDivide(B, A, L)
[0, 0
0, 0]
```
"""
function MatricesForHomalg.SafeRightDivide(B::Singular.smatrix, A::Singular.smatrix, L::Singular.smatrix)
    return Singular.transpose(MatricesForHomalg.SafeLeftDivide(Singular.transpose(A), Singular.transpose(B), Singular.transpose(L)))
end

"""
    RightDivide(B::Singular.smatrix, A::Singular.smatrix, L::Singular.smatrix)

Find X such that B - X * A is in the row span of L,
or return `"fail"` if no such X exists.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, R(0)], [R(0), y]], 2, 2, R);

julia> L = HomalgMatrix([[R(1), R(0)], [R(0), R(1)]], 2, 2, R);

julia> B = HomalgMatrix([[x^2, R(0)], [R(0), y^2]], 2, 2, R);

julia> RightDivide(B, A, L)
[0, 0
0, 0]
```
"""
function MatricesForHomalg.RightDivide(B::Singular.smatrix, A::Singular.smatrix, L::Singular.smatrix)
    try
        return MatricesForHomalg.SafeRightDivide(B, A, L)
    catch
        return "fail"
    end
end

## ReducedSyzygiesOfRows / ReducedSyzygiesOfColumns

"""
    ReducedSyzygiesOfColumns(A::Singular.smatrix)

Return a fully reduced Gröbner basis for the column syzygy module of A.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, x^2, x*y], [y, y^2, x*y]], 2, 3, R);

julia> S = ReducedSyzygiesOfColumns(A)
[x + y
-1
-1]

julia> iszero(A * S)
true
```
"""
function MatricesForHomalg.ReducedSyzygiesOfColumns(A::Singular.smatrix)
    M = Singular.Module(A)
    S = Singular.syz(M)
    if Singular.iszero(S)
        R = Singular.base_ring(A)
        return Singular.zero_matrix(R, Singular.ncols(A), 0)
    end
    G = Singular.std(S; complete_reduction=true)
    return Singular.Matrix(G)
end

"""
    ReducedSyzygiesOfRows(A::Singular.smatrix)

Return a fully reduced Gröbner basis for the row syzygy module of A.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2], [x*y, x*y]], 3, 2, R);

julia> S = ReducedSyzygiesOfRows(A)
[x + y, -1, -1]

julia> iszero(S * A)
true
```
"""
function MatricesForHomalg.ReducedSyzygiesOfRows(A::Singular.smatrix)
    return Singular.transpose(MatricesForHomalg.ReducedSyzygiesOfColumns(Singular.transpose(A)))
end

"""
    ReducedSyzygiesOfColumns(A::Singular.smatrix, N::Singular.smatrix)

Return a fully reduced Gröbner basis for the relative column syzygy module of A modulo N.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, x^2], [y, y^2]], 2, 2, R);

julia> N = HomalgMatrix([[x], [y]], 2, 1, R);

julia> ReducedSyzygiesOfColumns(A, N)
[1
0]
```
"""
function MatricesForHomalg.ReducedSyzygiesOfColumns(A::Singular.smatrix, N::Singular.smatrix)
    M_A = Singular.Module(A)
    M_N = Singular.Module(N)
    S = Singular.modulo(M_A, M_N)
    if Singular.iszero(S)
        R = Singular.base_ring(A)
        return Singular.zero_matrix(R, Singular.ncols(A), 0)
    end
    G = Singular.std(S; complete_reduction=true)
    return Singular.Matrix(G)
end

"""
    ReducedSyzygiesOfRows(A::Singular.smatrix, N::Singular.smatrix)

Return a fully reduced Gröbner basis for the relative row syzygy module of A modulo N.

```jldoctest
julia> using Singular, MatricesForHomalg

julia> R, (x, y) = Singular.polynomial_ring(Singular.QQ, ["x", "y"]);

julia> A = HomalgMatrix([[x, y], [x^2, y^2], [x*y, x*y]], 3, 2, R);

julia> N = HomalgMatrix([[x, y]], 1, 2, R);

julia> ReducedSyzygiesOfRows(A, N)
[1, 0, 0
0, 1, 1]
```
"""
function MatricesForHomalg.ReducedSyzygiesOfRows(A::Singular.smatrix, N::Singular.smatrix)
    return Singular.transpose(MatricesForHomalg.ReducedSyzygiesOfColumns(Singular.transpose(A), Singular.transpose(N)))
end

end # module
